<a href="https://colab.research.google.com/github/gaeldesenvolvedorgis-coder/shapely_estudos/blob/main/shapely_estudo_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from shapely.geometry import Point
import geopandas as gpd

1. Crie os pontos

In [ ]:
p1=Point(2,5)
p2=Point(2,6)
p3=Point(2,7)
p4=Point(2,8)
p5=Point(2,9)

2. Monte o GeoDataFrame

In [ ]:
gdf = gpd.GeoDataFrame({
        'nome':['Cidade A','Cidade B','Cidade C', 'Cidade D', 'Cidade E'],
        'populacao': [120000,100000,150000,180000,200000],
        'altitude': [450, 370, 485, 257 ,356],
        'geometry':[p1,p2,p3,p4,p5]
    },crs='EPSG:4326')

3. Faça consultas

In [ ]:
gdf[gdf['populacao'] >= 150000]

       nome  populacao  altitude     geometry
2  Cidade C     150000       485  POINT (2 7)
3  Cidade D     180000       257  POINT (2 8)
4  Cidade E     200000       356  POINT (2 9)

In [ ]:
gdf[gdf['altitude'] >= 400]

       nome  populacao  altitude     geometry
0  Cidade A     120000       450  POINT (2 5)
2  Cidade C     150000       485  POINT (2 7)

In [ ]:
gdf[gdf['nome'] == 'Cidade A']

       nome  populacao  altitude     geometry
0  Cidade A     120000       450  POINT (2 5)

4. Crie uma nova coluna

In [ ]:
gdf['densidade'] = (gdf['populacao']/gdf['altitude'])

In [ ]:
gdf[gdf['densidade'] <= 300]

       nome  populacao  altitude     geometry   densidade
0  Cidade A     120000       450  POINT (2 5)  266.666667
1  Cidade B     100000       370  POINT (2 6)  270.270270